# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC_servant.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gRPC_servant.proto\"\x19\n\x06Result\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x07Request\x12\x13\n\x0brequestName\x18\x01 \x01(\t2g\n\x0cgRPC_servant\x12\x1f\n\x08read_csv\x12\x08.Request\x1a\x07.Result\"\x00\x12\x1a\n\x03min\x12\x08.Request\x1a\x07.Result\"\x00\x12\x1a\n\x03max\x12\x08.Request\x1a\x07.Result\"\x00\x62\x06proto3')



_RESULT = DESCRIPTOR.message_types_by_name['Result']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'gRPC_servant_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'gRPC_servant_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

_GRPC_SERVANT = DESCRIPTOR.services_by_name['gRPC_servant']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESULT._serialized_start=22
  _RESULT._serialized_end=47
  _REQUEST._serialized_start=49
  _REQUEST._serialized_end=79
  _GRPC_SERVANT._serialized_start=81
  _GRPC_SERVANT._serialized_end=184
# @@protoc_insertion_point(module_scope)
