# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC_master.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gRPC_master.proto\"\x1d\n\rListedServers\x12\x0c\n\x04list\x18\x01 \x03(\t\"\"\n\x0fReturnedMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x07Request\x12\x13\n\x0brequestName\x18\x01 \x01(\t2\x8f\x01\n\x0bgRPC_master\x12(\n\x08\x61\x64\x64_node\x12\x08.Request\x1a\x10.ReturnedMessage\"\x00\x12+\n\x0bremove_node\x12\x08.Request\x1a\x10.ReturnedMessage\"\x00\x12)\n\x0bget_workers\x12\x08.Request\x1a\x0e.ListedServers\"\x00\x62\x06proto3')



_LISTEDSERVERS = DESCRIPTOR.message_types_by_name['ListedServers']
_RETURNEDMESSAGE = DESCRIPTOR.message_types_by_name['ReturnedMessage']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
ListedServers = _reflection.GeneratedProtocolMessageType('ListedServers', (_message.Message,), {
  'DESCRIPTOR' : _LISTEDSERVERS,
  '__module__' : 'gRPC_master_pb2'
  # @@protoc_insertion_point(class_scope:ListedServers)
  })
_sym_db.RegisterMessage(ListedServers)

ReturnedMessage = _reflection.GeneratedProtocolMessageType('ReturnedMessage', (_message.Message,), {
  'DESCRIPTOR' : _RETURNEDMESSAGE,
  '__module__' : 'gRPC_master_pb2'
  # @@protoc_insertion_point(class_scope:ReturnedMessage)
  })
_sym_db.RegisterMessage(ReturnedMessage)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'gRPC_master_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

_GRPC_MASTER = DESCRIPTOR.services_by_name['gRPC_master']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTEDSERVERS._serialized_start=21
  _LISTEDSERVERS._serialized_end=50
  _RETURNEDMESSAGE._serialized_start=52
  _RETURNEDMESSAGE._serialized_end=86
  _REQUEST._serialized_start=88
  _REQUEST._serialized_end=118
  _GRPC_MASTER._serialized_start=121
  _GRPC_MASTER._serialized_end=264
# @@protoc_insertion_point(module_scope)
