# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InsultAPI.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fInsultAPI.proto\"!\n\x11InsultListMessage\x12\x0c\n\x04list\x18\x01 \x03(\t\"$\n\x11RandInsultMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x07Request\x12\x13\n\x0brequestName\x18\x01 \x01(\t2\x92\x01\n\tInsultAPI\x12,\n\ngetInsults\x12\x08.Request\x1a\x12.InsultListMessage\"\x00\x12*\n\x08insultme\x12\x08.Request\x1a\x12.RandInsultMessage\"\x00\x12+\n\taddInsult\x12\x08.Request\x1a\x12.RandInsultMessage\"\x00\x62\x06proto3')



_INSULTLISTMESSAGE = DESCRIPTOR.message_types_by_name['InsultListMessage']
_RANDINSULTMESSAGE = DESCRIPTOR.message_types_by_name['RandInsultMessage']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
InsultListMessage = _reflection.GeneratedProtocolMessageType('InsultListMessage', (_message.Message,), {
  'DESCRIPTOR' : _INSULTLISTMESSAGE,
  '__module__' : 'InsultAPI_pb2'
  # @@protoc_insertion_point(class_scope:InsultListMessage)
  })
_sym_db.RegisterMessage(InsultListMessage)

RandInsultMessage = _reflection.GeneratedProtocolMessageType('RandInsultMessage', (_message.Message,), {
  'DESCRIPTOR' : _RANDINSULTMESSAGE,
  '__module__' : 'InsultAPI_pb2'
  # @@protoc_insertion_point(class_scope:RandInsultMessage)
  })
_sym_db.RegisterMessage(RandInsultMessage)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'InsultAPI_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

_INSULTAPI = DESCRIPTOR.services_by_name['InsultAPI']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSULTLISTMESSAGE._serialized_start=19
  _INSULTLISTMESSAGE._serialized_end=52
  _RANDINSULTMESSAGE._serialized_start=54
  _RANDINSULTMESSAGE._serialized_end=90
  _REQUEST._serialized_start=92
  _REQUEST._serialized_end=122
  _INSULTAPI._serialized_start=125
  _INSULTAPI._serialized_end=271
# @@protoc_insertion_point(module_scope)
