# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InsultAPI.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fInsultAPI.proto\"\'\n\x07Insults\x12\x0c\n\x04list\x18\x01 \x03(\t\x12\x0e\n\x06listed\x18\x02 \x01(\t2/\n\tInsultAPI\x12\"\n\ngetInsults\x12\x08.Insults\x1a\x08.Insults\"\x00\x62\x06proto3')



_INSULTS = DESCRIPTOR.message_types_by_name['Insults']
Insults = _reflection.GeneratedProtocolMessageType('Insults', (_message.Message,), {
  'DESCRIPTOR' : _INSULTS,
  '__module__' : 'InsultAPI_pb2'
  # @@protoc_insertion_point(class_scope:Insults)
  })
_sym_db.RegisterMessage(Insults)

_INSULTAPI = DESCRIPTOR.services_by_name['InsultAPI']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSULTS._serialized_start=19
  _INSULTS._serialized_end=58
  _INSULTAPI._serialized_start=60
  _INSULTAPI._serialized_end=107
# @@protoc_insertion_point(module_scope)
