# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import InsultAPI_pb2 as InsultAPI__pb2


class InsultAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getInsults = channel.unary_unary(
                '/InsultAPI/getInsults',
                request_serializer=InsultAPI__pb2.Insults.SerializeToString,
                response_deserializer=InsultAPI__pb2.Insults.FromString,
                )


class InsultAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getInsults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsultAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getInsults': grpc.unary_unary_rpc_method_handler(
                    servicer.getInsults,
                    request_deserializer=InsultAPI__pb2.Insults.FromString,
                    response_serializer=InsultAPI__pb2.Insults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InsultAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InsultAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getInsults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InsultAPI/getInsults',
            InsultAPI__pb2.Insults.SerializeToString,
            InsultAPI__pb2.Insults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
